[server]
enableStaticServing = true

headless = true                 # Run Streamlit in headless mode (no browser window will open automatically)
port = 8502                     # Specify the port to run the app on (default: 8501)
enableCORS = false              # Disable Cross-Origin Resource Sharing (CORS) protection
enableXsrfProtection = false
baseUrlPath = "/emailNewsBuilder"  # Set a custom base URL path for the app (default: "/")
#address="0.0.0.0"
